import{a as w,i,S as m}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function p(e,r=1){const o="48269176-9eacf4bd75a8a580043143bd0",n="https://pixabay.com/api/";try{return(await w.get(n,{params:{key:o,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(t){throw new Error(`Something went wrong: ${t.message}`)}}function b(e){return`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-item-image" />
        <div class="info">
          <p class="info-title">Likes:<span class="info-value">${e.likes}</span></p>
          <p class="info-title">Views:<span class="info-value">${e.views}</span></p>
          <p class="info-title">Comments:<span class="info-value">${e.comments}</span></p>
          <p class="info-title">Downloads:<span class="info-value">${e.downloads}</span></p>
        </div>
      </a>
    </li>
  `}function g(e){return e.map(b).join("")}const L=document.querySelector(".search-form"),d=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".load-more");let a=1,l="";c();L.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.searchQuery.value.trim(),!l){i.info({title:"No data",message:"Please enter a search query"});return}d.innerHTML="",a=1,h();try{const r=await p(l,a);if(!r.hits.length){i.error({title:"No result",message:"Sorry, no images matching your search query. Please try again!"}),c();return}const o=g(r.hits);d.insertAdjacentHTML("beforeend",o),new m(".gallery a").refresh(),r.totalHits>a*15&&(f.style.display="block")}catch(r){i.warning({title:"Error",message:`Something went wrong. ${r.message}`})}finally{c()}});f.addEventListener("click",async()=>{a+=1,h();try{const e=await p(l,a),r=g(e.hits);d.insertAdjacentHTML("beforeend",r),new m(".gallery a").refresh(),e.totalHits<=a*15&&(f.style.display="none",i.info({title:"End of results",message:"Sorry, but you've reached the end of search results."})),window.scrollBy({top:window.innerHeight,behavior:"smooth"})}catch(e){i.warning({title:"Error",message:`Something went wrong. ${e.message}`})}finally{c()}});function h(){y.style.display="block"}function c(){y.style.display="none"}
//# sourceMappingURL=index.js.map
